version: '3.8'

services:
  # Serviço Backend (Laravel)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netshowme_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - 8000:8000
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=netshowme_backend
      - DB_USERNAME=renan
      - DB_PASSWORD=sua_senha
    depends_on:
      - db
    command: >
      sh -c "while ! mysqladmin ping -h db --silent; do sleep 1; done &&
            composer install &&
            php artisan migrate &&
            php artisan serve --host=0.0.0.0 --port=8000"

  # Serviço Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netshowme_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  # Serviço Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: netshowme_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netshowme_backend
      MYSQL_USER: renan
      MYSQL_PASSWORD: sua_senha
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  # Serviço Webserver (Nginx)
  webserver:
    image: nginx:latest
    container_name: netshowme_webserver
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db_data:
